version: '3.5'

services:
    nginx:
        image: nginx:latest

        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts_debug:/etc/nginx/conf.d
            - ./www:/var/www/
            - ./logs:/var/log/nginx

        links:
            - php
        depends_on:
          - php
        working_dir: /var/www/
    php:
        build:
            context: .
            dockerfile: images/php/Dockerfile
        ports:
            - "222:22"

        links:
            - mysql
        
        volumes:
            - ./www:/var/www
        environment:
            XDEBUG_CONFIG: remote_host=192.168.43.101
    mysql:
        image: mysql:8

        ports:
            - "3306:3306"

        volumes:
            - ./mysql:/var/lib/mysql
            - ./mysql-dump:/docker-entrypoint-initdb.d

        environment:
            MYSQL_ROOT_PASSWORD: 123
            # bPSpAl2WPdevCC706k5Z
